include:
 - project: acc-co/devops/python/acc-py-devtools
   file: acc_py_devtools/templates/gitlab-ci/python.yml

variables:
  project_name: demo


# A full installation of pyqt-mega-tutorial-for-be-bi, tested with pytest.
test_install:
  extends: .acc_py_full_test


# A development installation of pyqt-mega-tutorial-for-be-bi tested with pytest.
test_dev:
  extends: .acc_py_dev_test


# A push of the source distribution to the acc-py PyPI, only on git tag.
release_sdist_on_tag:
  extends: .acc_py_release_sdist


# A dev build of the documentation, made available through cern.ch/acc-py.
build_docs:
  extends: .acc_py_build_docs


# A release build of the documentation, made available through cern.ch/acc-py.
build_docs_on_tag:
  extends: .acc_py_build_docs_on_tag
